# Automatically generated by configure - do not modify
SRC_PATH=/home/sc/workspace/os/run-linux/qemu-2.7zwx/qemu-2.7.0-original/roms/vgabios
AS=as
CCAS=cc
CC=cc
BCC=bcc
CPP=cc -E
OBJCOPY=objcopy
IASL=iasl
LD=ld
